### ISSUE TITLE
Google cloud platform support

### ISSUE THREAD

**Issue by renghen-p** [cyberark/kubeletctl#8] opened 2020-07-21 12:45 UTC
Hi 
How can I make it work with my k8s on google cloud, or any other cloud

**Comment by g3rzi** [comment] 2020-07-21 14:44
Hi,

It depends how it was configured.
Choose one of the nodes you want to check the kubelet inside them.  
The default kubelet configuration is `/var/lib/kubelet/config.yaml`, open it and check two things:
1. `authentication: anonymous: enabled: ?`
Is it set to `true`, `false` or neither?
2. `authorization: mode: ?`
Is it set to `AlwaysAllow`, `Webhook` or other?

I assume that GKE uses the secured option which is `authentication: anonymous: enabled: true` and `authorization: mode: Webhook`, in this case you need to use user with permissions.  

You can do it with the kubeconfig file which usually have the admin user like that:
```
kubeletctl -k ~/.kube/config -s <target_node_ip>
```

Another option is to user that have permissions and its certificates:
```
kubeletctl pods -s <node_ip> --cacert /etc/kubernetes/pki/ca.crt --cert <user_cert> --key <user_key>
```

Currently we are not support token authentication and authorization.

Let me know if it help you

**Comment by renghen** [comment] 2020-07-21 17:38
I got a tls: failed to find any PEM data in certificate input

kinda lost here :(

**Comment by g3rzi** [comment] 2020-07-21 20:47
Does it work if you use the kube config file?

**Comment by renghen** [comment] 2020-07-22 10:20
no it does not, but kubectl works fine

I am kinda lost here

**Comment by g3rzi** [comment] 2020-07-22 10:31
What are the settings of the `/var/lib/kubelet/config.yaml` ? 
Specifically the settings under `authentication: anonymous: enabled:` and `authorization: mode:`.

Can you show me the command your run + the output?

**Comment by renghen** [comment] 2020-07-23 09:01
hi 

I do not have a /var/lib/kubelet/config.yaml

and the command is kubeletctl configz -k ~/.kube/config
the output is 
2020/07/23 13:00:43 tls: failed to find any PEM data in certificate input

**Comment by g3rzi** [comment] 2020-07-25 07:49
Can you verify your CA bundle (section of the certificates) in the config YAML is the base64-encoded version of the PEM-bundle (so that base-64-decoding what is in the YAML/JSON displays PEM content)?

Example, the `certificate-authority-data`, `client-certificate-data` and `client-key-data` should be in base64:
![image](https://user-images.githubusercontent.com/11998736/88452050-42bdae00-ce64-11ea-884d-5793c2ca2e64.png)


When you base64-decode the CA bundle content, do you get PEM content like this:  
```
-----BEGIN CERTIFICATE-----
MIID...
```

**Comment by g3rzi** [comment] 2020-09-03 07:27
@renghen Any update?

**Comment by renghen** [comment] 2020-09-03 16:42
I do not have the users part for certificate. That is I do not have client-certificate-data

**Comment by g3rzi** [comment] 2022-09-12 06:20
@renghen can you share the structure of your config file? 
Sorry for the late response, we were able to reproduce it and fix it. We found that the issue is caused by wrong data in the config file.

**Comment by g3rzi** [comment] 2022-09-18 15:42
We are closing it for now.
If it happens again, please share the structure of your config file, the problem seems to be with a wrong config structure or wrong PEM inside it.

**Closed as completed by g3rzi** 2022-09-18 15:42 UTC
